cmake_minimum_required(VERSION 3.21)
project(TieredCacheConsumer LANGUAGES CXX)
set(SUB0TIEREDCACHE_BUILD_TESTING OFF CACHE BOOL "")
set(SUB0MEMPAGE_BUILD_TESTING OFF CACHE BOOL "")
if(PROVIDE_MEMPAGE)
  add_subdirectory("${FETCHCONTENT_SOURCE_DIR_SUB0MEMPAGE}" mempage)
endif()
add_subdirectory("${TIEREDCACHE_SOURCE_DIR}" tieredcache)
add_executable(consumer main.cpp)
target_link_libraries(consumer PRIVATE Sub0TieredCache::Sub0TieredCache)
